config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipient_manager.urls', namespace='home')),
    path('messages/', include('message_manager.urls', namespace='message_manager')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='user')),
]

mailing/urls.py
from mailing.apps import MailingConfig
from .views import (MailingCreateView, MailingDeleteView, MailingDetailView, MailingUpdateView, MailingListView,
                    MailingSendView, AttemptMailingDetailView, MailingStatisticsView, AttemptMailingView, BlockingMailingView)
from django.urls import path, include


app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/send/', MailingSendView.as_view(), name='send'),
    path('attempts/<int:mailing_id>', AttemptMailingView.as_view(), name='attempt_list'),
    path('attempts/<int:pk>/', AttemptMailingDetailView.as_view(), name='attempt_detail'),
    path('statistics/', MailingStatisticsView.as_view(), name='user_statistics'),
    path('<int:pk>/blocking/', BlockingMailingView.as_view(), name='blocking_mailing'),

]

message_manager/urls.py
from django.urls import path, include
from .views import MessageListView, MessageCreateView, MessageDeleteView, MessageDetailView, MessageUpdateView
from .apps import MessageManagerConfig

app_name = MessageManagerConfig.name

urlpatterns = [
    path('', MessageListView.as_view(), name='messages_list'),
    path('<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('create/', MessageCreateView.as_view(), name='message_create'),
    path('<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

]

recipient_manager/urls.py
from django.urls import path

from recipient_manager.apps import UserManagerConfig
from recipient_manager.views import (MailingRecipientListView, HomeView, MailingRecipientDetailView,
                                     MailingRecipientCreateView, MailingRecipientDeleteView, MailingRecipientUpdateView)

app_name = UserManagerConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('recipients/', MailingRecipientListView.as_view(), name='recipient_list'),
    path('recipients/create/', MailingRecipientCreateView.as_view(), name='recipient_create'),
    path('recipients/<int:pk>/', MailingRecipientDetailView.as_view(), name='recipient_detail'),
    path('recipients/<int:pk>/delete/', MailingRecipientDeleteView.as_view(), name='recipient_delete'),
    path('recipients/<int:pk>/update/', MailingRecipientUpdateView.as_view(), name='recipient_update'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, TemplateView
from .views import (UserRegisterView, custom_logout, PasswordResetView,
                    ConfirmRegistrationView, PasswordResetRequestView,
                    UsersListView, UsersDetailView, BlockingUsersView,  )

from .apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', custom_logout, name='logout'),
    path('confirm/<str:token>/', ConfirmRegistrationView.as_view(), name='confirm_registration'),
    path('password_reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password_reset/done/', TemplateView.as_view(template_name='users/password_reset_request.html'), name='password_reset_done'),
    path('reset/<str:token>/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/complete/', TemplateView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/', UsersListView.as_view(), name='users_list'),
    path('user/<int:pk>/blocking/', BlockingUsersView.as_view(), name='blocking_user')

]

recipient_manager/models.py
from django.db import models


from users.models import User


class MailingRecipient(models.Model):

    email = models.EmailField(unique=True, verbose_name='Email')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(blank=True, null=True)
    recipient_owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец карточки клиента', blank=True, null=True)

    class Meta:
        verbose_name = 'Получатель рассылки'
        verbose_name_plural = 'Получатели рассылки'


    def __str__(self):
        return self.email

recipient_manager/forms.py
from django import forms

from .models import MailingRecipient


class MailingRecipientForm(forms.ModelForm):
    class Meta:
        model = MailingRecipient
        fields = ['email', 'fio', 'comment']

recipient_manager/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from mailing.models import Mailing
from .forms import MailingRecipientForm
from .models import MailingRecipient
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import DetailView, ListView, TemplateView, CreateView, DeleteView, UpdateView, View


class MailingRecipientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = MailingRecipient
    template_name = 'recipient_manager/recipient_list.html'
    context_object_name = 'recipients'
    permission_required = 'recipient_manager.view_mailingrecipient'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('recipient.view_recipient') or not user == self.object.owner:
            raise PermissionDenied

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.groups.filter(name='moder').exists():
            return qs
        return qs.filter(recipient_owner=self.request.user)


class MailingRecipientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = MailingRecipient
    template_name = 'recipient_manager/recipient_detail.html'
    context_object_name = 'recipient'
    pk_url_kwarg = 'pk'
    permission_required = 'recipient_manager.view_mailingrecipient'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('recipient_manager.view_recipient') or not user == self.object.owner:
            raise PermissionDenied


class MailingRecipientCreateView(LoginRequiredMixin, CreateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    template_name = 'recipient_manager/recipient_form.html'
    success_url = reverse_lazy('recipient_manager:recipient_list')

    def form_valid(self, form):
        form.instance.recipient_owner = self.request.user
        return super().form_valid(form)


class MailingRecipientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):

    model = MailingRecipient
    template_name = 'recipient_manager/recipient_delete.html'
    context_object_name = 'recipient'
    pk_url_kwarg = 'pk'
    permission_required = 'recipient_manager.can_delete_mailingrecipient'

    def has_permission(self):
        user = self.request.user
        self.object = self.get_object()
        if not user.has_perm('recipient_manager.delete_mailingrecipient') or not user == self.object.recipient_owner:
            raise False
        return True


class MailingRecipientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    model = MailingRecipient
    form_class = MailingRecipientForm
    template_name = 'recipient_manager/recipient_form.html'
    success_url = reverse_lazy('recipient_manager:recipient_list')
    permission_required = 'recipient_manager.change_mailingrecipient'

    def has_permission(self):
        user = self.request.user
        self.object = self.get_object()
        if not user.has_perm('recipient_manager.change_mailingrecipient') or not user == self.object.recipient_owner:
            raise False
        return True


class HomeView(TemplateView):
    template_name = 'recipient_manager/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)


        context['total_mailings'] = Mailing.objects.count()


        context['active_mailings'] = Mailing.objects.filter(status='Running').count()


        context['unique_recipients'] = MailingRecipient.objects.count()  # или оптимизированный запрос

        return context

recipient_manager/templates/recipient_manager/includes/custom_style.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

recipient_manager/templates/recipient_manager/includes/footer.html
<p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2024 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>

recipient_manager/templates/recipient_manager/includes/inc_header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'recipient_manager:home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'recipient_manager:recipient_list' %}">Recipients</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'message_manager:messages_list' %}">Messages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mailing:mailing_list' %}">Mailing</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mailing:user_statistics' %}">'Statistics'</a>
          </li>
          {% else %}
          {% endif %}
          {% if perms.users.list_user %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:users_list' %}">Users</a>
          </li>
          {% else %}
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
          </li>

            {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Зарегистрироваться</a>
          </li>

            {% endif %}
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>