config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipient_manager.urls', namespace='home')),
    path('messages/', include('message_manager.urls', namespace='message_manager')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='user')),
]

mailing/urls.py
from mailing.apps import MailingConfig
from .views import (MailingCreateView, MailingDeleteView, MailingDetailView, MailingUpdateView, MailingListView,
                    MailingSendView, AttemptMailingDetailView, MailingStatisticsView, AttemptMailingView, BlockingMailingView)
from django.urls import path, include


app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/send/', MailingSendView.as_view(), name='send'),
    path('attempts/<int:mailing_id>', AttemptMailingView.as_view(), name='attempt_list'),
    path('attempts/<int:pk>/', AttemptMailingDetailView.as_view(), name='attempt_detail'),
    path('statistics/', MailingStatisticsView.as_view(), name='user_statistics'),
    path('<int:pk>/blocking/', BlockingMailingView.as_view(), name='blocking_mailing'),

]

message_manager/urls.py
from django.urls import path, include
from .views import MessageListView, MessageCreateView, MessageDeleteView, MessageDetailView, MessageUpdateView
from .apps import MessageManagerConfig

app_name = MessageManagerConfig.name

urlpatterns = [
    path('', MessageListView.as_view(), name='messages_list'),
    path('<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('create/', MessageCreateView.as_view(), name='message_create'),
    path('<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

]

recipient_manager/urls.py
from django.urls import path

from recipient_manager.apps import UserManagerConfig
from recipient_manager.views import (MailingRecipientListView, HomeView, MailingRecipientDetailView,
                                     MailingRecipientCreateView, MailingRecipientDeleteView, MailingRecipientUpdateView)

app_name = UserManagerConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('recipients/', MailingRecipientListView.as_view(), name='recipient_list'),
    path('recipients/create/', MailingRecipientCreateView.as_view(), name='recipient_create'),
    path('recipients/<int:pk>/', MailingRecipientDetailView.as_view(), name='recipient_detail'),
    path('recipients/<int:pk>/delete/', MailingRecipientDeleteView.as_view(), name='recipient_delete'),
    path('recipients/<int:pk>/update/', MailingRecipientUpdateView.as_view(), name='recipient_update'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, TemplateView
from .views import (UserRegisterView, custom_logout, PasswordResetView,
                    ConfirmRegistrationView, PasswordResetRequestView,
                    UsersListView, UsersDetailView, BlockingUsersView,  )

from .apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', custom_logout, name='logout'),
    path('confirm/<str:token>/', ConfirmRegistrationView.as_view(), name='confirm_registration'),
    path('password_reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password_reset/done/', TemplateView.as_view(template_name='users/password_reset_request.html'), name='password_reset_done'),
    path('reset/<str:token>/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/complete/', TemplateView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/', UsersListView.as_view(), name='users_list'),
    path('user/<int:pk>/blocking/', BlockingUsersView.as_view(), name='blocking_user')

]

recipient_manager/models.py
from django.db import models


from users.models import User


class MailingRecipient(models.Model):

    email = models.EmailField(unique=True, verbose_name='Email')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(blank=True, null=True)
    recipient_owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец карточки клиента', blank=True, null=True)

    class Meta:
        verbose_name = 'Получатель рассылки'
        verbose_name_plural = 'Получатели рассылки'


    def __str__(self):
        return self.email

recipient_manager/forms.py
from django import forms

from .models import MailingRecipient


class MailingRecipientForm(forms.ModelForm):
    class Meta:
        model = MailingRecipient
        fields = ['email', 'fio', 'comment']

recipient_manager/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from mailing.models import Mailing
from .forms import MailingRecipientForm
from .models import MailingRecipient
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic import DetailView, ListView, TemplateView, CreateView, DeleteView, UpdateView, View


class MailingRecipientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = MailingRecipient
    template_name = 'recipient_manager/recipient_list.html'
    context_object_name = 'recipients'
    permission_required = 'recipient_manager.view_mailingrecipient'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('recipient.view_recipient') or not user == self.object.owner:
            raise PermissionDenied

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.groups.filter(name='moder').exists():
            return qs
        return qs.filter(recipient_owner=self.request.user)


class MailingRecipientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = MailingRecipient
    template_name = 'recipient_manager/recipient_detail.html'
    context_object_name = 'recipient'
    pk_url_kwarg = 'pk'
    permission_required = 'recipient_manager.view_mailingrecipient'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('recipient_manager.view_recipient') or not user == self.object.owner:
            raise PermissionDenied


class MailingRecipientCreateView(LoginRequiredMixin, CreateView):
    model = MailingRecipient
    form_class = MailingRecipientForm
    template_name = 'recipient_manager/recipient_form.html'
    success_url = reverse_lazy('recipient_manager:recipient_list')

    def form_valid(self, form):
        form.instance.recipient_owner = self.request.user
        return super().form_valid(form)


class MailingRecipientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):

    model = MailingRecipient
    template_name = 'recipient_manager/recipient_delete.html'
    context_object_name = 'recipient'
    pk_url_kwarg = 'pk'
    permission_required = 'recipient_manager.can_delete_mailingrecipient'

    def has_permission(self):
        user = self.request.user
        self.object = self.get_object()
        if not user.has_perm('recipient_manager.delete_mailingrecipient') or not user == self.object.recipient_owner:
            raise False
        return True


class MailingRecipientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):

    model = MailingRecipient
    form_class = MailingRecipientForm
    template_name = 'recipient_manager/recipient_form.html'
    success_url = reverse_lazy('recipient_manager:recipient_list')
    permission_required = 'recipient_manager.change_mailingrecipient'

    def has_permission(self):
        user = self.request.user
        self.object = self.get_object()
        if not user.has_perm('recipient_manager.change_mailingrecipient') or not user == self.object.recipient_owner:
            raise False
        return True


class HomeView(TemplateView):
    template_name = 'recipient_manager/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)


        context['total_mailings'] = Mailing.objects.count()


        context['active_mailings'] = Mailing.objects.filter(status='Running').count()


        context['unique_recipients'] = MailingRecipient.objects.count()  # или оптимизированный запрос

        return context

recipient_manager/templates/recipient_manager/home.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Carousel Template · Bootstrap v5.3</title>

    <link rel="canonical" href="{% static 'css/carousel.css' %}">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<!--<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">-->
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
  </head>
  <body>
  {% include 'recipient_manager/includes/custom_style.html' %}


<header data-bs-theme="dark">
  {% include 'recipient_manager/includes/inc_header.html' %}
</header>

<main>

  <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Общее количество рассылок</h1>
            <p>{{ total_mailings }}</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'mailing:mailing_list' %}">Рассылки</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Количество активных рассылок</h1>
            <p>{{ active_mailings }}</p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <div class="container">
          <div class="carousel-caption text-end">
            <h1>Количество уникальных получателей</h1>
            <p>{{ unique_recipients }}</p>
            <p><a class="btn btn-lg btn-primary" href="{% url 'recipient_manager:recipient_list' %}">Клиенты</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <h2 class="fw-normal">Recipient</h2>
        <p>Тут ты сможешь создать нового клиента для рассылок.</p>
        <p><a class="btn btn-secondary" href="{% url 'recipient_manager:recipient_create' %}">Создать &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <h2 class="fw-normal">Messages</h2>
        <p>Здесь создаются новые сообщения для рассылок.</p>
        <p><a class="btn btn-secondary" href="{% url 'message_manager:message_create' %}">Создать &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"/></svg>
        <h2 class="fw-normal">Mailing</h2>
        <p>Создайте свою рассылку</p>
        <p><a class="btn btn-secondary" href="{% url 'mailing:mailing_create' %}">Создать &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->



    {% block content %}
    {% endblock %}



  <!-- FOOTER -->

<footer class="text-body-secondary py-5">
  {% include 'recipient_manager/includes/footer.html' %}
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>

    </body>
</html>

recipient_manager/templates/recipient_manager/recipient_delete.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Удалить объект </title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Удалить объект </h1>
        <p>Вы уверены, что хотите удалить "{{ recipient.email }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Удалить</button>
            <a href="{% url 'recipient_manager:recipient_detail' recipient.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

recipient_manager/templates/recipient_manager/recipient_detail.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">{{ recipient.fio}} <span class="text-body-secondary">{{ recipient.email}}</span></h2>
        <p class="lead">{{recipient.comment }}</p>
         {% if perms.recipient.change_recipient or user == recipient.owner %}

        <a class="btn btn-primary" href="{% url 'recipient_manager:recipient_update' recipient.pk %}" role="button">Изменить</a>
          {% endif %}
        {% if perms.recipient.delete_recipient or user == recipient.owner %}

        <a class="btn btn-primary" href="{% url 'recipient_manager:recipient_delete' recipient.pk %}" role="button">Удалить</a>
          {% endif %}
      </div>
    </div>
{% endblock %}

recipient_manager/templates/recipient_manager/recipient_form.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

recipient_manager/templates/recipient_manager/recipient_list.html
{% extends 'recipient_manager/home.html'%}
{% block content %}

{% for recipient in recipients %}
<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">{{ recipient.fio}} <span class="text-body-secondary">{{ recipient.email}}</span></h2>
        <p class="lead">{{recipient.comment }}</p>
        {% if perms.recipient_manager.view_recipient or user == recipient.owner %}
        <a class="btn btn-primary" href="{{ recipient.id }}" role="button">Подробнее</a>
        {% endif %}
      </div>
    </div>
{% endfor %}
{% endblock %}