config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipient_manager.urls', namespace='home')),
    path('messages/', include('message_manager.urls', namespace='message_manager')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='user')),
]

mailing/urls.py
from mailing.apps import MailingConfig
from .views import (MailingCreateView, MailingDeleteView, MailingDetailView, MailingUpdateView, MailingListView,
                    MailingSendView, AttemptMailingDetailView, MailingStatisticsView, AttemptMailingView, BlockingMailingView)
from django.urls import path, include


app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('<int:pk>/delete', MailingDeleteView.as_view(), name='mailing_delete'),
    path('<int:pk>/send/', MailingSendView.as_view(), name='send'),
    path('attempts/<int:mailing_id>', AttemptMailingView.as_view(), name='attempt_list'),
    path('attempts/<int:pk>/', AttemptMailingDetailView.as_view(), name='attempt_detail'),
    path('statistics/', MailingStatisticsView.as_view(), name='user_statistics'),
    path('<int:pk>/blocking/', BlockingMailingView.as_view(), name='blocking_mailing'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, TemplateView
from .views import (UserRegisterView, custom_logout, PasswordResetView,
                    ConfirmRegistrationView, PasswordResetRequestView,
                    UsersListView, UsersDetailView, BlockingUsersView,  )

from .apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', custom_logout, name='logout'),
    path('confirm/<str:token>/', ConfirmRegistrationView.as_view(), name='confirm_registration'),
    path('password_reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password_reset/done/', TemplateView.as_view(template_name='users/password_reset_request.html'), name='password_reset_done'),
    path('reset/<str:token>/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/complete/', TemplateView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/', UsersListView.as_view(), name='users_list'),
    path('user/<int:pk>/blocking/', BlockingUsersView.as_view(), name='blocking_user')

]

mailing/models.py
from django.db import models
from recipient_manager.models import MailingRecipient
from message_manager.models import Message
from users.models import User


class Mailing(models.Model):

    date_first_sending = models.DateField(verbose_name='Дата первой отправки', blank=True, null=True)
    date_end_shipment = models.DateField(verbose_name='Дата окончание отправки', blank=True, null=True)
    status = models.CharField(max_length=20, choices=[
        ('Completed', 'Completed'),
        ('Create', 'Create'),
        ('Running', 'Running')
    ])
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')
    recipient = models.ManyToManyField(MailingRecipient)
    mailing_owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец рассылки', blank=True, null=True)
    is_active = models.BooleanField(verbose_name='Активность рассылки/Блокировка рассылки', default=True)

    def __str__(self):
        return f'Рассылка {self.id}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('block_mailing', 'Блокировка рассылки'),
        ]


class AttemptMailing(models.Model):

    attempt_date = models.DateField(verbose_name='Дата и время попытки отправки')
    status = models.CharField(max_length=20, choices=[
        ('Successful', 'Successful'),
        ('Unsuccessful', 'Unsuccessful')
    ])
    status_response = models.TextField(blank=True, null=True)
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')

mailing/forms.py
from .models import Mailing
from django import forms


class MailingForm(forms.ModelForm):

    class Meta:
        model = Mailing
        fields = ['message', 'recipient']

#class MailingModeratorForm(forms.ModelForm):
#    class Meta:
#        model = Mailing
#        fields = ['message','recipient']

class BlockingMailing(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ['is_active',]

mailing/views.py
from django.utils import timezone

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, DeleteView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from .forms import MailingForm, BlockingMailing
from .models import Mailing, AttemptMailing
from django.http import HttpResponse
from django.core.management import call_command
from django.db.models import Count, Q
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator


class MailingCreateView(LoginRequiredMixin, CreateView):

    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        form.instance.status = 'Create'
        form.instance.mailing_owner = self.request.user
        return super().form_valid(form)


@method_decorator(cache_page(60 * 15), name='dispatch')
class MailingListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'mailings'
    permission_required = 'mailing.view_mailing'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('mailing.view_mailing') or not user == self.object.owner:
            raise PermissionDenied

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.groups.filter(name='moder').exists():
            return qs
        return qs.filter(mailing_owner=self.request.user)

class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'
    context_object_name = 'mailing'
    pk_url_kwarg = 'pk'
    permission_required = 'mailing.view_mailing'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('mailing.view_mailing') or not user == self.object.owner:
            raise PermissionDenied


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.change_mailing'

    def has_permission(self):
        self.object = self.get_object()
        user = self.request.user
        if not user.has_perm('mailing.change_mailing') or not user == self.object.mailing_owner:
            raise False
        return True


class BlockingMailingView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = BlockingMailing
    template_name = 'mailing/mailing_block_form.html'
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.block_mailing'

    def get_form_class(self):
        user = self.request.user
        if user.has_perm('mailing.block_mailing'):
            return BlockingMailing
        else:
            raise PermissionDenied


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    template_name = 'mailing/mailing_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')
    permission_required = 'mailing.delete_mailing'

    def has_permission(self):
        user = self.request.user
        self.object = self.get_object()
        if not user.has_perm('mailing.delete_mailing') or not user == self.object.mailing_owner:
            raise False
        return True


class MailingSendView(LoginRequiredMixin, DetailView):
    model = Mailing
    pk_url_kwarg = 'pk'
    template_name = 'mailing/mailing_send.html'

    def get(self, request, *args, **kwargs):
        mailing = self.get_object()
        return render(request, self.template_name, {'mailing': mailing})

    def save_attempt(self, mailing, status, status_response=None, recipient=None):
        attempt = AttemptMailing(mailing=mailing, attempt_date=timezone.now(), status=status)

        if recipient:
            attempt.status_response.append(f'{recipient} {status_response}')

        elif status_response:
            attempt.status_response = status_response

        attempt.save()

    def post(self, request, *args, **kwargs):
        mailing = self.get_object()

        try:
            call_command('send_mailing', mailing.pk)
            return HttpResponse('Рассылка успешно отправлена', status=200)

        except Exception as e:

            self.save_attempt(mailing, 'Unsuccessful', e)
            return HttpResponse('Ошибка при отправке рассылки', status=500)


class AttemptMailingView(LoginRequiredMixin, View):
    template_name = 'attempt/attempt_mg_list.html'

    def get(self, request, mailing_id):
        mailing = get_object_or_404(Mailing, pk=mailing_id)
        attempts = AttemptMailing.objects.filter(mailing=mailing)

        context = {
            'mailing': mailing,
            'attempts': attempts,
        }
        return render(request, self.template_name, context)


class AttemptMailingListView(LoginRequiredMixin, ListView):
    model = AttemptMailing
    template_name = 'attempt/attempt_list.html'
    context_object_name = 'attempts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing'] = self.mailing
        return context


class AttemptMailingDetailView(LoginRequiredMixin, DetailView):
    model = AttemptMailing
    template_name = 'attempt/attempt_detail.html'
    context_object_name = 'attempt'
    pk_url_kwarg = 'pk'


class MailingStatisticsView(LoginRequiredMixin, View):
    template_name = 'mailing/user_statistics.html'

    def get_mailing_statistics(self, user):

        mailings = Mailing.objects.filter(mailing_owner=user)
        statistics = mailings.annotate(
            successful_attempts=Count('attemptmailing', filter=Q(attemptmailing__status='Successful')),
            unsuccessful_attempts=Count('attemptmailing', filter=Q(attemptmailing__status='Unsuccessful')),
            total_messages=Count('recipient')
        )
        result = []
        for mailing in statistics:
            result.append({
                'mailing_id': mailing.id,
                'date_first_sending': mailing.date_first_sending,
                'successful_attempts': mailing.successful_attempts,
                'unsuccessful_attempts': mailing.unsuccessful_attempts,
                'total_messages': mailing.total_messages,
            })
        return result

    def get_user_mailing_summary(self, user):

        attempts = AttemptMailing.objects.filter(mailing__mailing_owner=user)
        summary = attempts.aggregate(
            total_successful=Count('id', filter=Q(status='Successful')),
            total_unsuccessful=Count('id', filter=Q(status='Unsuccessful')),
            total_messages=Count('mailing__recipient', distinct=True)
        )
        return summary

    def get(self, request):
        user = request.user

        mailing_stats = self.get_mailing_statistics(user)

        user_summary = self.get_user_mailing_summary(user)

        context = {
            'mailing_stats': mailing_stats,
            'user_summary': user_summary,
        }

        return render(request, self.template_name, context)

mailing/templates/mailing/mailing_block_form.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <h2>Блокировка id mailing: {{ mailing.id}} {{ mailing.message.subject}}</h2>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    {% if mailing.is_active %}
                    <button type="submit" class="btn btn-primary">
                        Разблокировать
                    </button>
                    {% else %}
                    <button type="submit" class="btn btn-primary">
                        Заблокировать
                    </button>
                    {% endif%}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_delete.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Удалить объект </title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Удалить объект </h1>
        <p>Вы уверены, что хотите удалить "{{ mailing.subject }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:mailing_detail' mailing.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'recipient_manager/home.html'%}
{% block content %}


<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">{{ mailing.id}} </h2>
        <p class="lead">{{mailing.date_first_sending }}</p>
        <p class="lead">{{mailing.date_end_shipment }}</p>
        <p class="lead">{{mailing.status }}</p>
        <p class="lead">{{mailing.message.subject }}</p>
        <p class="lead">Recipients
        <ul> {% for recipient in mailing.recipient.all %}
              <li> {{ recipient.email }} </li>
            {% endfor %}
      </ul>
        </p>
          {% if perms.mailing.send_mailing or user == mailing.mailing_owner %}
        <a class="btn btn-primary" href="{% url 'mailing:send' mailing.pk %}" role="button">Отправить рассылку</a>
          {% endif %}
          {% if perms.mailing.change_mailing or user == mailing.mailing_owner %}
        <a class="btn btn-primary" href="{% url 'mailing:mailing_update' mailing.pk %}" role="button">Изменить</a>
          {% endif %}
          {% if perms.mailing.delete_mailing or user == mailing.mailing_owner %}
        <a class="btn btn-primary" href="{% url 'mailing:mailing_delete' mailing.pk %}" role="button">Удалить</a>
          {% endif %}
        <a class="btn btn-primary" href="{% url 'mailing:attempt_list' mailing.pk %}" role="button">Попытки</a>
         {% if perms.mailing.block_mailing %}
        <a class="btn btn-primary" href="{% url 'mailing:blocking_mailing' mailing.pk %}" role="button">Заблокировать</a>
          {% endif %}
      </div>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'recipient_manager/home.html'%}
{% block content %}

{% for mailing in mailings %}
<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">{{ mailing.id}} </h2>
        <p class="lead">{{mailing.status }}</p>
        <p class="lead">{{mailing.message.subject }}</p>
          {% if perms.mailing.view_mailing or user == mailing.mailing_owner %}
        <a class="btn btn-primary" href="{{ mailing.pk }}" role="button">Подробнее</a>
          {% endif %}
      </div>
    </div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/mailing_send.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Отправка рассылки </title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Отправка рассылки </h1>
        <p>Вы уверены, что хотите отправить эту рассылку?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Отправить</button>
            <a href="{% url 'mailing:mailing_detail' mailing.pk %}" class="btn btn-secondary">Отмена</a>
        </form>

    {% if success_message %}
        <p>{{ success_message }}</p>

    {% endif %}

    {% if error_message %}
        <p style="color: red;">{{ error_message }}</p>
    {% endif %}
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

mailing/templates/mailing/user_statistics.html
{% extends 'recipient_manager/home.html'%}

{% block content %}

<!DOCTYPE html>
<html>
<head>
    <title>Статистика рассылок</title>
</head>
<body>
    <h1>Общая статистика</h1>
    <p>Успешных попыток: {{ user_summary.total_successful }}</p>
    <p>Неуспешных попыток: {{ user_summary.total_unsuccessful }}</p>
    <p>Всего отправлено сообщений: {{ user_summary.total_messages }}</p>

    <h1>Статистика по рассылкам</h1>
    <table>
        <tr>
            <th>ID рассылки</th>
            <th>Дата первой отправки</th>
            <th>Успешные попытки</th>
            <th>Неуспешные попытки</th>
            <th>Всего сообщений</th>
            <th>Подробнее</th>

        </tr>
        {% for stat in mailing_stats %}
        <tr>
            <td>{{ stat.mailing_id }}</td>
            <td>{{ stat.date_first_sending }}</td>
            <td>{{ stat.successful_attempts }}</td>
            <td>{{ stat.unsuccessful_attempts }}</td>
            <td>{{ stat.total_messages }}</td>
            <td>
                <a href="{% url 'mailing:attempt_detail' stat.mailing_id %}" class="btn btn-primary">Посмотреть</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

{% endblock %}