config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipient_manager.urls', namespace='home')),
    path('messages/', include('message_manager.urls', namespace='message_manager')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='user')),
]

message_manager/urls.py
from django.urls import path, include
from .views import MessageListView, MessageCreateView, MessageDeleteView, MessageDetailView, MessageUpdateView
from .apps import MessageManagerConfig

app_name = MessageManagerConfig.name

urlpatterns = [
    path('', MessageListView.as_view(), name='messages_list'),
    path('<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('create/', MessageCreateView.as_view(), name='message_create'),
    path('<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, TemplateView
from .views import (UserRegisterView, custom_logout, PasswordResetView,
                    ConfirmRegistrationView, PasswordResetRequestView,
                    UsersListView, UsersDetailView, BlockingUsersView,  )

from .apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', custom_logout, name='logout'),
    path('confirm/<str:token>/', ConfirmRegistrationView.as_view(), name='confirm_registration'),
    path('password_reset/', PasswordResetRequestView.as_view(), name='password_reset_request'),
    path('password_reset/done/', TemplateView.as_view(template_name='users/password_reset_request.html'), name='password_reset_done'),
    path('reset/<str:token>/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/complete/', TemplateView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('user/', UsersListView.as_view(), name='users_list'),
    path('user/<int:pk>/blocking/', BlockingUsersView.as_view(), name='blocking_user')

]

message_manager/models.py
from django.db import models

from users.models import User


class Message(models.Model):

    subject = models.CharField(max_length=50, verbose_name='Тема сообщения')
    body_text = models.TextField(blank=True, null=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Владелец рассылки', blank=True, null=True)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

message_manager/forms.py
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body_text']

message_manager/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, ListView, TemplateView, CreateView,  DeleteView, UpdateView, View
from .forms import MessageForm
from .models import Message
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'message_manager/message_form.html'
    success_url = reverse_lazy('message_manager:messages_list')

    def form_valid(self, form):
        form.instance.message_owner = self.request.user
        return super().form_valid(form)


#@method_decorator(cache_page(60 * 15), name='dispatch')
class MessageListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Message
    template_name = 'message_manager/messages_list.html'
    context_object_name = 'messages'
    permission_required = 'message_manager.view_message'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('message_manager.view_message') or not user == self.object.owner:
            raise PermissionDenied

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.groups.filter(name='moder').exists():
            return qs
        return qs.filter(owner=self.request.user)

class MessageDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Message
    template_name = 'message_manager/message_detail.html'
    context_object_name = 'message'
    pk_url_kwarg = 'pk'
    permission_required = 'message_manager.view_message'

    def get_form_class(self):
        user = self.request.user
        if not user.has_perm('message_manager.view_message') or not user == self.object.owner:
            raise PermissionDenied


class MessageUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'message_manager/message_form.html'
    success_url = reverse_lazy('recipient_manager:home')
    permission_required = 'message_manager.change_message'

    def has_permission(self):
        self.object = self.get_object()
        user = self.request.user
        if user == self.object.owner:
            return MessageForm
        if not user.has_perm('message_manager.change_message') or not user == self.object.owner:
            raise PermissionDenied


class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):

    model = Message
    template_name = 'message_manager/message_delete.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('recipient_manager:home')
    permission_required = 'message_manager.can_delete_message'

    def has_permission(self):
        self.object = self.get_object()
        user = self.request.user
        if user == self.object.owner:
            return MessageForm
        if not user.has_perm('message_manager.change_message') or not user == self.object.owner:
            raise PermissionDenied

message_manager/templates/message_manager/message_delete.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Удалить объект </title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-4">Удалить объект </h1>
        <p>Вы уверены, что хотите удалить "{{ message.subject }}"?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'message_manager:message_detail' message.pk %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>
{% endblock %}

message_manager/templates/message_manager/message_detail.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
         <h2 class="featurette-heading fw-normal lh-1">{{ message.subject}}</h2>
        <p class="lead">{{message.body_text }}</p>
          {% if perms.message_manager.change_message or user == message.owner %}
        <a class="btn btn-primary" href="{% url 'message_manager:message_update' message.pk %}" role="button">Изменить</a>
          {% endif %}
          {% if perms.message_manager.delete_message or user == message.owner %}
        <a class="btn btn-primary" href="{% url 'message_manager:message_delete' message.pk %}" role="button">Удалить</a>
          {% endif %}
      </div>
    </div>
{% endblock %}

message_manager/templates/message_manager/message_form.html
{% extends 'recipient_manager/home.html'%}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

message_manager/templates/message_manager/message_list.html
{% extends 'recipient_manager/home.html'%}
{% block content %}

{% for message in messages %}
<hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">{{ message.subject}}</h2>
        <p class="lead">{{message.body_text|truncatechars:50 }}</p>
          {% if perms.message_manager.view_message or user == message.owner %}
        <a class="btn btn-primary" href="{{ message.id }}" role="button">Подробнее</a>
          {% endif %}
      </div>
    </div>
{% endfor %}
{% endblock %}